config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get root 'events#index'

  resources :users, only: [:show]
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :event_participation_email
	belongs_to :user, required: false
    belongs_to :event, required: false

    def event_participation_email
		UserMailer.event_participation_email(self.user, self.event).deliver_now
	end
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :attendances
    has_many :users, through: :attendances
    belongs_to :admin, class_name: "User", required: false

	validates :start_date, presence: true 
    validate :start_date_not_before_time_now
    validates :duration, presence: true, :numericality => { greater_than: 0 }
    validate :duration_minutes 
	validates :title, presence: true, length: { in: 5..140, message: "Un titre fait entre 5 et 140 caractères" }
	validates :description, presence: true, length: { in: 20..1000, message: "Un description fait entre 20 et 1000 caractères" }
	validates :price, presence: true, length: { in: 1..1000, message: "Le prix doit etre compris entre 1 et 1000 €" } 
	validates :location, presence: true 


	def start_date_not_before_time_now #Méthode pour ne pas entrer une date antérieur à la date de debut 
	    if start_date < Date.today
            errors.add(:start_date, "la date ne doit pas etre dans le passé") 
        end  
    end

    def duration_minutes #met l'entre de duree de l'even en positif multiple de 5
        unless duration.present? && duration > 0 && duration % 5 == 0
            errors.add(:duration, "la durée doit etre positive et multiple de 5")
          end
     end

end

	#def start_date_not_before_time_now
    	#unless start_date.present? && start_date > DateTime.now
      		#errors.add(:start_date, "La date ne peut pas etre inférieure à aujourd'hui")
    	#end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :welcome_send
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

	#has_many :attendances
	#has_many :events, foreign_key: 'admin_id', class_name: "Event"

	has_many :events, through: :attendances 
  has_many :events, foreign_key: 'admin_id', class_name: "User"
   
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end




# Un utilisateur peut participer à plusieurs événements au travers des participations. 
# Un utilisateur peut administrer plusieurs événements.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
  end
  
  def new 
  	@event = Event.new
  end 

  def create
    @event = Event.new('title' => params[:event_title], 'location' => params[:event_location], 'description' => params[:event_description], 'start_date' => params[:event_date], 'price' => params[:event_price].to_i, 'duration' => params[:event_duration].to_i)
    @event.admin = current_user
    
    if @event.save
      redirect_to events_path, notice: "L'événement #{@event.title} a bien été créé ! Bien joué petit génie !"
    else
      redirect_to new_event_path, alert: "Dommage, certaines informations sont incorrectes : le titre doit faire entre 3 et 30 caractères. "
    end
  end
  
  private

  def authenticate_current_user
    unless current_user == Gossip.find(params[:id]).user
      redirect_to gossip_path(params[:id]), alert: "Vous ne pouvez pas modifier ce potin"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params['id'])
    puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    puts @user
    @user_events = Event.where(admin_id: @user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>The EvenBrides - Index</title>


</head>
<body>
  
  <main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron" style="background-image: url(<%= 'https://technext.github.io/Evento/images/demo/bg-slide-01.jpg' %>)"
    <div class="container">
      <h1 class="display-3">Bienvenue sur EvenBrides</h1>
      <p>Que l'immersion commence!</p>
      <p><%= button_to "Créer un Event", events_path, class:"btn btn-light", :method => :get %></p>
      <p><%= button_to "Participer à un Event", events_path, class:"btn btn-light", :method => :get %></p>
    </div>
  </div>


  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Voici les Events disponibles:</h1>
    <p class="lead">Choisi ton Event</p>
  </div>
      
  <div class="container">
    <div class="row">
      <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
        <ul class="event-list" >
          <% Event.all.each_with_index do |event, i| %>
            <li>
              <time datetime=<%= event.start_date %>>
                <span class="day"> <%= event.start_date.day %> </span>
                <span class="month"> <%= event.start_date.strftime('%b') %> </span>
                <span class="year"> <%= event.start_date.year %> </span>
                <span class="time"> </span>
              </time>
              <div class="info">
                <h2 class="title"><%= event.title %></h2>
                <p class="desc"><a href="<%= event_path(event.id) %>"> <%= event.description %> </a></p>
                <ul>
                  <li style="width:50%;"><a href="#website"><span class="fa fa-globe"></span> Website</a></li>
                  <li style="width:50%;"><span class="fa fa-money"></span> <%= event.price %> €</li>
                </ul>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  </div>
</body>
</html>

app/views/events/new.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Créer un événement</title>
  </head>
<body>
  <!-- Message d'erreur en cas de problème-->
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <p>Nous n'avons pas réussi à créer l'event pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
          <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  
  <!-- Formulaire création évènement -->
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">  
        <br><br><br>
        <h1>Création événement</h1>

        <%= form_tag url_for(action: 'create'), method: "post" do %>

          <div class="form-group">
            <%= label_tag 'Renseigne un titre : ' %>
            <%= text_field_tag :event_title %>
          </div>

          <div class="form-group">
            <%= label_tag 'Indique un lieu : ' %>
            <%= text_field_tag :event_location %>
          </div>

          <div class="form-group">
            <%= label_tag 'Met ta description : ' %>
            <%= text_area_tag :event_description %>
          </div>

          <div class="form-group">
            <%= label_tag 'Indique une date : ' %>
            <%= date_field_tag :event_date %>
          </div>
          
          <div class="form-group">
            <%= label_tag 'Balance un prix : ' %>
            <%= text_field_tag :event_price %>
          </div>

          <div class="form-group">
            <%= label_tag 'Complète avec une durée (en minutes, multiple de 5) : ' %>
            <%= text_field_tag :event_duration %>
          </div>

          <div class="actions mt-5">
            <%= submit_tag("Create Event", :class =>"btn btn-primary") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvenbridesV1</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
      <script src="https://kit.fontawesome.com/46962466a1.js" crossorigin="anonymous"></script>
 
      <!--//  \/ligne bootstrap copier depuis le projet de semaine 1 \/-->
      <link rel="stylesheet" href="/app/stylesheets/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-success bg-light">
    
    <div class="column">
      <img src="https://cdn.logojoy.com/wp-content/uploads/2018/05/30163918/1241-768x591.png" class="img-fluid">
    </div>
    
    <div class="navbar-brand column ml-4">
      <%= link_to "Evenbrides", events_path %>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse" id="navbarSupportedContent">
      
      <ul class="navbar-nav mr-auto">
        
          <div class='container-navbar pl-3'>
                
            <li class="nav-item active">
              <div class="nav-link pl-3"><%= link_to "Créer un Event", new_event_path %> </div>
            </li>

            <li class="nav-item active">
              <div class="nav-link pl-3"><%= link_to "Participer à un Event", events_path %> </div>
            </li>  
          </div>
      </ul>
          <div class="dropdown pr-5 mr-3">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profil
            </a>
          
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <% if user_signed_in? %>
                  <li class="dropdown-item">
                    <%= link_to "Mon profil", user_path(current_user) %>
                  </li>
                  <li class="dropdown-item">
                    <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
                  </li>
                <% else %>
                  <li class="dropdown-item">
                    <%= link_to "S'inscrire ", new_user_registration_path %>
                  </li>
                  <li class="dropdown-item">
                    <%= link_to "Se connecter", new_user_session_path %>
                  </li>
                <% end %>
            </div>             
              
                  
          </div>
          
        </div>
      
    </div>
     
    </nav>

    <%= yield %>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/show.html.erb
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>The Evenbrides App - User</title>
    </head>

    <body>
    
        <div class="container" style= "margin-bottom: 45px">
            <div class="row">
                <div class="col-sm-12 ">
                    <h2 class="card-title "> Profil <%=@user.first_name%></h2>
                    
                    <p>Prénom : <%=@user.first_name %></p>
                    <p>Nom : <%=@user.last_name %></p>
                    <p>Description : <%= @user.description %></p>
                    <p>Email : <%= @user.email %></p>
                    </p>
                </div>
            </div>
        </div>
        
        <div class="container" style= "margin-bottom: 25px">
            <div class="row">
                <div class="col-sm-12">
                    <h4>Je suis inscrit aux Events suivants:</h4>
                </div>
                <div class="col-sm-12 ">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">Evénement</th>
                            <th scope="col">Page de l'événément</th>
                        </tr>
                        </thead>
                        <tbody>
                            <% @user_events.each do |event| %>
                        <tr>
                            <td><%=event.title %></td>
                            <td><%= link_to 'Détail', event_path(event.id), class: 'btn btn-secondary bg-info' %></td>
                        </tr>
                        <tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    <h4>Mes événements en tant qu'organisateur:</h4>
                </div>
                <div class="col-sm-12 ">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">Evénement</th>
                            <th scope="col">Page de l'événément</th>
                        </tr>
                        </thead>
                        <tbody>
                            <% @user_events.each do |event| %>
                        <tr>
                            <td><%=event.title %></td>
                            <td><%= link_to "Voir plus", event_path(event.id) %></td>
                        </tr>
                        <tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>